from __future__ import annotations

STAGE_SURFACES = {
    "stage0": {
        "label": "Stage 0",
        "description": "Convert an autoregressive base into a diffusion-native backbone.",
        "accent": "violet",
        "defaults": {
            "model": "openbmb/MiniCPM5-2B-Base",
            "world_size": 4,
            "device": "cuda",
            "dtype": "bf16",
            "parameters": {
                "steps": 10000,
                "micro_batch_size": 1,
                "target_global_batch_size": 96,
                "learning_rate": 2e-5,
                "weight_decay": 0.1,
                "warmup_ratio": 0.0,
                "lr_schedule": "constant",
                "checkpoint_every": 250,
                "keep_checkpoints": 2,
                "cpu_offload": True,
                "gradient_checkpointing": True,
                "fsdp_no_sync_accumulation": True,
                "aggressive_prefetch": True,
                "export_hf": True,
            },
        },
    },
    "stage-a": {
        "label": "Stage A",
        "description": "Train CID modules while keeping the diffusion backbone frozen.",
        "accent": "cyan",
        "defaults": {
            "model": "GSAI-ML/iLLaDA-8B-Base",
            "world_size": 4,
            "device": "cuda",
            "dtype": "bf16",
            "parameters": {
                "epochs": 3,
                "learning_rate": 1e-4,
                "weight_decay": 0.01,
                "micro_batch_size": 1,
                "target_global_batch_size": 96,
                "max_grad_norm": 1.0,
                "rollout_horizon": 3,
                "thought_capacity": 128,
                "max_display_tokens": 1536,
                "display_canvas_tokens": 64,
                "log_every_steps": 100,
                "checkpoint_every_steps": 5000,
                "gradient_checkpointing": True,
            },
        },
    },
    "stage-b": {
        "label": "Stage B",
        "description": "Continue with full-parameter FSDP training after Stage A.",
        "accent": "amber",
        "defaults": {
            "model": "GSAI-ML/iLLaDA-8B-Base",
            "world_size": 4,
            "device": "cuda",
            "dtype": "bf16",
            "parameters": {
                "epochs": 1,
                "learning_rate": 2e-5,
                "backbone_lr_scale": 0.25,
                "weight_decay": 0.01,
                "target_global_batch_size": 32,
                "warmup_ratio": 0.01,
                "lr_schedule": "wsd-linear",
                "wsd_decay_ratio": 0.1,
                "min_learning_rate_ratio": 0.1,
                "rollout_horizon": 3,
                "thought_capacity": 128,
                "max_display_tokens": 1536,
                "display_canvas_tokens": 64,
                "log_every_steps": 100,
                "checkpoint_every_steps": 2500,
                "fsdp_cpu_offload": False,
                "fsdp_no_sync_accumulation": False,
                "fsdp_aggressive_prefetch": False,
            },
        },
    },
}
